project:
  type: website
  output-dir: _site

format:
  html:
    include-in-header:
      - text: |
          <script>
          window.MathJax = {
            tex: {
              tags: 'ams'
            }
          };
          </script>